# Generated by Django 6.0.3 on 2026-04-15 22:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('curso', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('departamento', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('semestre', models.CharField(help_text='Ex.: 2026.1', max_length=10)),
                ('alunos', models.ManyToManyField(blank=True, related_name='disciplinas', to='core.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas', to='core.professor')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('predio', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('raio_permitido', models.PositiveIntegerField(default=50, help_text='Raio em metros')),
            ],
            options={
                'ordering': ['predio', 'nome'],
                'unique_together': {('predio', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('token_qrcode', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='core.disciplina')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='core.sala')),
            ],
            options={
                'ordering': ['-data', '-horario_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_registro', models.DateTimeField(auto_now_add=True)),
                ('ip_registrado', models.GenericIPAddressField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADA', 'Justificada')], default='PRESENTE', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='core.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='core.aula')),
            ],
            options={
                'ordering': ['-horario_registro'],
                'unique_together': {('aluno', 'aula')},
            },
        ),
    ]
