# Generated by Django 6.0.3 on 2026-04-22 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='data_fim',
            field=models.DateField(blank=True, help_text='Fim do semestre', null=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='data_inicio',
            field=models.DateField(blank=True, help_text='Início do semestre', null=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='dias_semana',
            field=models.CharField(blank=True, default='', help_text='Dias da semana em que há aula (CSV: MON,TUE,...)', max_length=30),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='horario_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='sala_padrao',
            field=models.ForeignKey(blank=True, help_text='Sala onde as aulas ocorrem normalmente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='core.sala'),
        ),
    ]
