# Generated by Django 6.0.3 on 2026-04-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_disciplina_data_fim_disciplina_data_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='dias_semana',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='horario_fim',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='horario_inicio',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='sala_padrao',
        ),
    ]
